import json
from pathlib import Path

import cv2
import ffmpeg
from loguru import logger

from slides_vqa.config import SLIDE_TIMESTAMPS_PROMPT


def split_video_into_chunks(input_video: str, output_dir: str, chunk_seconds: int):
    """
    Splits a video into chunks of a specified duration.

    Args:
        input_video: Path to the input video file.
        output_dir: Directory where the chunks will be saved.
        chunk_seconds: Duration of each chunk in seconds.
    """
    try:
        (
            ffmpeg.input(input_video)
            .output(
                str(Path(output_dir) / "%03d.mp4"),
                c="copy",
                map="0",
                segment_time=chunk_seconds,
                f="segment",
            )
            .run(capture_stdout=True, capture_stderr=True)
        )
    except ffmpeg.Error as e:
        print(f"stdout: {e.stdout.decode('utf8')}")
        print(f"stderr: {e.stderr.decode('utf8')}")
        raise e


def find_slide_timestamps(
    model, chunks_dir: str, slide_timestamps_prompt: str = SLIDE_TIMESTAMPS_PROMPT
):
    """Find the timestamps of the slide changes in a chunk.

    Process all chunks inside `chunks_dir`.

    Args:
        model: The model to use to extract the timestamps.
        chunks_dir: Directory containing the video chunks.
        slide_timestamps_prompt: Prompt to use to extract the timestamps.

    Returns:
        None. Writes the timestamps to a JSON file for each chunk.
    """
    chunks_dir = Path(chunks_dir)
    for chunk in chunks_dir.glob("*.mp4"):
        yield f"Processing {chunk}"
        slide_timestamps = model.process_video(
            str(chunk), prompt=slide_timestamps_prompt
        )
        (chunks_dir / f"{chunk.stem}.json").write_text(slide_timestamps)


def time_to_seconds(time_str):
    """Converts a timestamp string (MM:SS) to seconds."""
    parts = list(map(int, time_str.split(":")))
    minutes, seconds = parts
    return minutes * 60 + seconds


def seconds_to_time(total_seconds):
    """Converts total seconds to MM:SS format."""
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    return f"{minutes:02d}:{seconds:02d}"


@logger.catch(reraise=True)
def merge_timestamps(chunks_dir: str, chunk_seconds: int):
    """Joins timestamps from multiple JSON files into a single list.

    Assumes that the timestamp files are numerically ordered, like
    the output generated by [extract_slide_timestamps][slides_vqa.preprocess_video.extract_slide_timestamps].

    Applies an offset to each timestamp based on the chunk it came from.

    Args:
        chunks_dir: Directory containing the JSON files.

            The expected format of each JSON file is:

            ```json
            [
                {"timestamp": "01:00", "title": "First slide", "description": "This slide displays the outline of the talk."},
                ...
            ]
            ```

        chunk_seconds: Duration of each chunk in seconds.

    Returns:
        A list of merged timestamps.
    """
    merged_timestamps = []
    file_list = sorted([str(f) for f in Path(chunks_dir).glob("*.json")])

    for file_index, filename in enumerate(file_list):
        chunk_offset_seconds = file_index * chunk_seconds

        with open(filename, "r") as f:
            data = json.load(f)

        for entry in data:
            relative_timestamp_str = entry["timestamp"]
            relative_seconds = time_to_seconds(relative_timestamp_str)
            absolute_seconds = relative_seconds + chunk_offset_seconds
            absolute_timestamp_str = seconds_to_time(absolute_seconds)

            merged_entry = {
                "timestamp": absolute_timestamp_str,
                "title": entry["title"],
                "description": entry["description"],
            }
            merged_timestamps.append(merged_entry)

    return merged_timestamps


def extract_slides(
    input_video: str, merged_timestamps: dict, output_dir: str, offset: int = 0
):
    """Extract slides from `input_video` based on `merged_timestamps`.

    Args:
        input_video: Path to the input video file.
        merged_timestamps: List of timestamps and slide information.
        output_dir: Directory where the slides will be saved.
        offset: Offset in seconds to add to the timestamp.

    Returns:
        A list of paths to the extracted slides.
    """
    cap = cv2.VideoCapture(input_video)

    output_files = []
    for slide in merged_timestamps:
        timestamp_str = slide["timestamp"]
        title = slide["title"]
        output_file = f"{output_dir}/{timestamp_str} - {title}.jpg"
        seconds = time_to_seconds(timestamp_str) + offset
        fps = cap.get(cv2.CAP_PROP_FPS)
        frame_number = int(seconds * fps)
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
        _, frame = cap.read()

        cv2.imwrite(output_file, frame)
        output_files.append(output_file)

    cap.release()
    return output_files
